file(GLOB ATTENDANCE_TEST_SOURCES CONFIGURE_DEPENDS
        "${CMAKE_CURRENT_SOURCE_DIR}/*.cpp"
)
file(GLOB ATTENDANCE_TEST_HEADERS CONFIGURE_DEPENDS
        "${CMAKE_CURRENT_SOURCE_DIR}/*.h"
)

foreach (ATTENDANCE_TEST_SOURCE IN LISTS ATTENDANCE_TEST_SOURCES)
    get_filename_component(ATTENDANCE_TEST_TARGET "${ATTENDANCE_TEST_SOURCE}" NAME_WE)

    add_executable(${ATTENDANCE_TEST_TARGET}
            "${ATTENDANCE_TEST_SOURCE}"
            ${ATTENDANCE_TEST_HEADERS}
    )

    target_link_libraries(${ATTENDANCE_TEST_TARGET} PRIVATE
            Attendance::Core
    )

    add_test(NAME ${ATTENDANCE_TEST_TARGET} COMMAND ${ATTENDANCE_TEST_TARGET})
    set_tests_properties(${ATTENDANCE_TEST_TARGET} PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=windows")
endforeach ()
